ARG MLFLOW_VERSION=v3.9.0
FROM ghcr.io/mlflow/mlflow:${MLFLOW_VERSION}

# install deps 
RUN pip install psycopg2-binary boto3

# copy over the startup script 
RUN mkdir /scripts/ 
COPY ./mlflow/startup.sh /scripts/startup.sh 
RUN chmod u+x /scripts/startup.sh

# start the mlflow server 
ENTRYPOINT [ "/scripts/startup.sh" ]
